image: node:16-alpine

stages:
  - update-production

deploy:
  stage: update-production
  only:
    - main
  script:
    - npm i -g @liara/cli@2
    - export http_proxy=http://proxy.liara.ir:6666
    - liara deploy --app $APP_NAME --detach --region iran --api-token $TOKEN
